// Vokabeln: [deutsch, português, kategorie]
// Konjugationen: erste Zeile = Grundform, folgende Zeilen = eu/tu/ele/nós/eles
// Neue Karte hinzufügen: ["Deutsch", "Português", "Kategorie"],
// Kategorien: Verben · Präteritum · Adjektive · Farben · Kleidung · Körper
//             Essen · Transport · Nomen · Orte · Wohnen · Familie · Zeit
//             Orientierung · Zahlen · Grammatik · Begrüßungen · Redewendungen

const rawCards = [
  // --- Verben ---
  ["studieren/lernen","estudar\nestudo\nestudas\nestuda\nestudamos\nestudam","Verben"],
  ["laufen / rennen","correr\ncorro\ncorres\ncorre\ncorremos\ncorrem","Verben"],
  ["eintreten / hereinkommen","entrar\nentro\nentras\nentra\nentramos\nentram","Verben"],
  ["tanzen","dançar\ndanço\ndanças\ndança\ndançamos\ndançam","Verben"],
  ["spazieren","caminhar\ncaminho\ncaminhas\ncaminha\ncaminhamos\ncaminham","Verben"],
  ["anschalten","ligar\nligo\nligas\nliga\nligamos\nligam","Verben"],
  ["singen","cantar\ncanto\ncantas\ncanta\ncantamos\ncantam","Verben"],
  ["kaufen","comprar\ncompro\ncompras\ncompra\ncompramos\ncompram","Verben"],
  ["essen","comer\ncomo\ncomes\ncome\ncomemos\ncomem","Verben"],
  ["kochen","cozinhar\ncozinho\ncozinhas\ncozinha\ncozinhamos\ncozinham","Verben"],
  ["verkaufen","vender\nvendo\nvendes\nvende\nvendemos\nvendem","Verben"],
  ["schreiben","escrever\nescrevo\nescreves\nescreve\nescrevemos\nescrevem","Verben"],
  ["erklären","explicar\nexplico\nexplicas\nexplica\nexplicamos\nexplicam","Verben"],
  ["helfen","ajudar\najudo\najudas\najuda\najudamos\najudam","Verben"],
  ["öffnen","abrir\nabro\nabres\nabre\nabrimos\nabrem","Verben"],
  ["schließen","fechar\nfecho\nfechas\nfecha\nfechamos\nfecham","Verben"],
  ["anhalten","parar\nparo\nparas\npara\nparamos\nparam","Verben"],
  ["abfahren / verlassen","partir\nparto\npartes\nparte\npartimos\npartem","Verben"],
  ["bringen (herbringen)","trazer\ntrago\ntrazes\ntraz\ntrazemos\ntrazem","Verben"],
  ["ausschalten","desligar\ndesligo\ndesligas\ndesliga\ndesligamos\ndesligam","Verben"],
  ["bezahlen","pagar\npago\npagas\npaga\npagamos\npagam","Verben"],
  ["reisen","viajar\nviajo\nviajas\nviaja\nviajamos\nviajam","Verben"],
  ["sprechen","falar\nfalo\nfalas\nfala\nfalamos\nfalam","Verben"],
  ["fühlen","sentir\nsinto\nsentes\nsente\nsentimos\nsentem","Verben"],
  ["geben","dar\ndou\ndás\ndá\ndamos\ndão","Verben"],
  ["lachen","rir\nrio\nris\nri\nrimos\nriem","Verben"],
  ["sein (permanent)","ser\nsou\nés\né\nsomos\nsão","Verben"],
  ["hören","ouvir\nouço\nouves\nouve\nouvimos\nouvem","Verben"],
  ["glauben / finden","achar\nacho\nachas\nacha\nachamos\nacham","Verben"],
  ["stellen/legen/setzen","pôr\nponho\npões\npõe\npomos\npõem","Verben"],
  ["denken","pensar\npenso\npensas\npensa\npensamos\npensam","Verben"],
  ["gehen","ir\nvou\nvais\nvai\nvamos\nvão","Verben"],
  ["verstehen","perceber/compreender\npercebo\npercebes\npercebe\npercebemos\npercebem","Verben"],
  ["warten / hoffen","esperar\nespero\nesperas\nespera\nesperamos\nesperam","Verben"],
  ["bitten/bestellen","pedir\npeço\npedes\npede\npedimos\npedem","Verben"],
  ["bleiben / werden","ficar\nfico\nficas\nfica\nficamos\nficam","Verben"],
  ["ankommen","chegar\nchego\nchegas\nchega\nchegamos\nchegam","Verben"],
  ["kommen (Ort)","vir\nvenho\nvens\nvem\nvimos\nvêm","Verben"],
  ["lesen","ler\nleio\nlês\nlê\nlemos\nleem","Verben"],
  ["antworten","responder\nrespondo\nrespondes\nresponde\nrespondemos\nrespondem","Verben"],
  ["machen","fazer\nfaço\nfazes\nfaz\nfazemos\nfazem","Verben"],
  ["vergessen","esquecer\nesqueço\nesqueces\nesquece\nesquecemos\nesquecem","Verben"],
  ["hinausgehen","sair\nsaio\nsais\nsai\nsaímos\nsaem","Verben"],
  ["bevorzugen","preferir\nprefiro\npreferes\nprefere\npreferimos\npreferem","Verben"],
  ["lernen","aprender\naprendo\naprendes\naprende\naprendemos\naprendem","Verben"],
  ["lernen (im Augenblick)","estudar\nestudo\nestudas\nestuda\nestudamos\nestudam","Verben"],
  ["schlafen","dormir\ndurmo\ndormes\ndorme\ndormimos\ndormem","Verben"],
  ["nehmen (Bus, Dusche)","tomar\ntomo\ntomas\ntoma\ntomamos\ntomam","Verben"],
  ["erinnern","lembrar\nlembro\nlembras\nlembra\nlembramos\nlembram","Verben"],
  ["brauchen","precisar (de)\npreciso\nprecisas\nprecisa\nprecisamos\nprecisam","Verben"],
  ["sehen","ver\nvejo\nvês\nvê\nvemos\nveem","Verben"],
  ["schauen","olhar\nolho\nolhas\nolha\nolhamos\nolham","Verben"],
  ["finden / treffen","encontrar\nencontro\nencontras\nencontra\nencontramos\nencontram","Verben"],
  ["rufen / nennen","chamar\nchamo\nchamas\nchama\nchamamos\nchamam","Verben"],
  ["parken","estacionar\nestaciono\nestacionas\nestaciona\nestacionamos\nestacionam","Verben"],
  ["können/dürfen","poder\nposso\npodes\npode\npodemos\npodem","Verben"],
  ["wissen","saber\nsei\nsabes\nsabe\nsabemos\nsabem","Verben"],
  ["sagen","dizer\ndigo\ndizes\ndiz\ndizemos\ndizem","Verben"],
  ["wollen","querer\nquero\nqueres\nquer\nqueremos\nquerem","Verben"],
  ["mögen","gostar (de)\ngosto\ngostas\ngosta\ngostamos\ngostam","Verben"],
  ["benutzen","usar\nuso\nusas\nusa\nusamos\nusam","Verben"],
  ["haben","ter\ntenho\ntens\ntem\ntemos\ntêm","Verben"],
  ["mitnehmen / tragen","levar\nlevo\nlevas\nleva\nlevamos\nlevam","Verben"],
  ["arbeiten","trabalhar\ntrabalho\ntrabalhas\ntrabalha\ntrabalhamos\ntrabalham","Verben"],
  ["fragen","perguntar\npergunto\nperguntas\npergunta\nperguntamos\nperguntam","Verben"],
  ["trinken","beber\nbebo\nbebes\nbebe\nbebemos\nbebem","Verben"],
  ["regnen","chover","Verben"],
  ["wohnen","morar\nmoro\nmoras\nmora\nmoramos\nmoram","Verben"],
  ["zu Abend essen","jantar\njanto\njantas\njanta\njantamos\njantam","Verben"],
  ["zu mittag essen","almoçar\nalmoço\nalmoças\nalmoça\nalmoçamos\nalmoçam","Verben"],
  ["Geburtstag haben","fazer anos","Verben"],
  ["im Urlaub sein","estar de férias","Verben"],
  ["einen Spaziergang machen","Dar uma volta","Verben"],
  ["sein (vorübergehend)","estar\nestou\nestás\nestá\nestamos\nestão","Verben"],
  ["leben","viver\nvivo\nvives\nvive\nvivemos\nvivem","Verben"],
  ["können (wissen wie)","conseguir\nconsigo\nconsegues\nconsegue\nconseguimos\nconseguem","Verben"],
  ["müssen / sollen","dever\ndevo\ndeves\ndeve\ndevemos\ndevem","Verben"],
  ["zurückkehren / wiederkommen","voltar\nvolto\nvoltas\nvolta\nvoltamos\nvoltam","Verben"],
  ["beginnen / anfangen","começar\ncomeço\ncomeças\ncomeça\ncomeçamos\ncomeçam","Verben"],
  ["aufhören / beenden","acabar / terminar\nacabo\nacabas\nacaba\nacabamos\nacabam","Verben"],
  ["kennen (Person/Ort)","conhecer\nconheço\nconheces\nconhece\nconhecemos\nconhecem","Verben"],
  ["versuchen","tentar\ntento\ntentas\ntenta\ntentamos\ntentam","Verben"],
  ["spielen","jogar / brincar\n(jogar = Sport/Spiel, brincar = als Kind spielen)","Verben"],
  ["sich ausruhen","descansar\ndescanso\ndescansas\ndescansa\ndescansamos\ndescansam","Verben"],
  ["sich waschen","lavar-se","Verben"],
  ["sich anziehen","vestir-se","Verben"],
  ["aufwachen","acordar\nacordo\nacordas\nacorda\nacordamos\nacordam","Verben"],
  ["einschlafen","adormecer\nadormeço\nadormeces\nadormece\nadormecemos\nadormecem","Verben"],
  ["sich beeilen","despachar-se","Verben"],
  ["reservieren / buchen","reservar\nreservo\nreservas\nreserva\nreservamos\nreservam","Verben"],
  ["ändern / wechseln","mudar\nmudo\nmudas\nmuda\nmudamos\nmudam","Verben"],
  ["folgen","seguir\nsigo\nsegues\nsegue\nseguimos\nseguem","Verben"],
  ["verlieren","perder\nperco\nperdes\nperde\nperdemos\nperdem","Verben"],
  ["gewinnen / verdienen","ganhar\nganho\nganhas\nganha\nganhamos\nganham","Verben"],
  ["zeigen","mostrar\nmostro\nmostras\nmostra\nmostramos\nmostram","Verben"],

  // --- Präteritum ---
  ["ich war (sein – estar)","estive\n(estive, estiveste, esteve, estivemos, estiveram)","Präteritum"],
  ["ich war (sein – ser)","fui\n(fui, foste, foi, fomos, foram)\n⚠ ser und ir teilen dieselben Vergangenheitsformen!","Präteritum"],
  ["ich hatte","tive\n(tive, tiveste, teve, tivemos, tiveram)","Präteritum"],
  ["ich machte","fiz\n(fiz, fizeste, fez, fizemos, fizeram)","Präteritum"],
  ["ich sagte","disse\n(disse, disseste, disse, dissemos, disseram)","Präteritum"],
  ["ich kam","vim\n(vim, vieste, veio, viemos, vieram)","Präteritum"],
  ["ich ging","fui\n(fui, foste, foi, fomos, foram)","Präteritum"],

  // --- Adjektive ---
  ["dünn","magro/a","Adjektive"],
  ["schläfrig","sono","Adjektive"],
  ["unsympathisch","antipático","Adjektive"],
  ["durstig","sede","Adjektive"],
  ["heiß (Umgebung)","calor","Adjektive"],
  ["groß/hoch","alto/a","Adjektive"],
  ["hässlich","feio","Adjektive"],
  ["kalt","frio","Adjektive"],
  ["schwer (Gewicht)","pesado","Adjektive"],
  ["wenig","pouco","Adjektive"],
  ["hungrig","fome","Adjektive"],
  ["klein","pequeno","Adjektive"],
  ["klein (Mensch)","baixo/a","Adjektive"],
  ["müde","cansada/o","Adjektive"],
  ["hübsch","bonito","Adjektive"],
  ["schmal","estreito","Adjektive"],
  ["leicht (Gewicht)","leve","Adjektive"],
  ["ängstlich","medo","Adjektive"],
  ["ruhig","calmo/a","Adjektive"],
  ["verheiratet","casado/a","Adjektive"],
  ["viel / sehr","muito","Adjektive"],
  ["laut","barulhento/a","Adjektive"],
  ["ruhig / leise","silencioso/a / sossegado/a","Adjektive"],
  ["sauber","limpo/a","Adjektive"],
  ["schmutzig","sujo/a","Adjektive"],
  ["schnell","rápido/a","Adjektive"],
  ["langsam","lento/a / devagar","Adjektive"],
  ["einfach / leicht","fácil","Adjektive"],
  ["schwierig / schwer","difícil","Adjektive"],
  ["neu","novo/a","Adjektive"],
  ["alt (Sachen)","velho/a / antigo/a","Adjektive"],
  ["gleich / selbe","mesmo/a / igual","Adjektive"],
  ["anders / verschieden","diferente / outro/a","Adjektive"],

  // --- Farben ---
  ["blau","azul/azuis","Farben"],
  ["schwarz","preto/preta","Farben"],
  ["weiß","branco/branca","Farben"],
  ["grau","cinzento/cinzenta","Farben"],
  ["gelb","amarelo/amarela","Farben"],
  ["grün","verde","Farben"],
  ["rot","vermelho/vermelha","Farben"],
  ["orange","cor de laranja","Farben"],
  ["pink","cor de rosa","Farben"],
  ["braun","castanho/castanha","Farben"],

  // --- Kleidung ---
  ["Pullover","a camisola","Kleidung"],
  ["Hemd","a camisa","Kleidung"],
  ["Hose","as calças","Kleidung"],
  ["Jacke/Mantel","o casaco","Kleidung"],
  ["Schuhe","os sapatos","Kleidung"],
  ["Jeans","calças de ganga","Kleidung"],
  ["Rock","a saia","Kleidung"],
  ["Kleidung","a roupa","Kleidung"],
  ["Brille","os óculos","Kleidung"],

  // --- Körper & Gesundheit ---
  ["Bart","a barba","Körper"],
  ["Schnautzer","bigode","Körper"],
  ["Augen","os olhos","Körper"],
  ["Haare","os cabelos","Körper"],
  ["Kopf","a cabeça","Körper"],
  ["Hand","a mão (Pl: as mãos)","Körper"],
  ["Arm","o braço","Körper"],
  ["Bein","a perna","Körper"],
  ["Fuß","o pé","Körper"],
  ["Rücken","as costas","Körper"],
  ["Bauch","a barriga","Körper"],
  ["Ich habe Schmerzen","Tenho dores / Dói-me...\n(z.B. Dói-me a cabeça = Kopfschmerzen)","Körper"],
  ["Ich fühle mich nicht gut","Não me sinto bem","Körper"],
  ["Ich habe Fieber","Tenho febre","Körper"],

  // --- Essen & Restaurant ---
  ["Brot","o pão","Essen"],
  ["Bier","a cerveja","Essen"],
  ["Kaffee","o café","Essen"],
  ["Wasser","a água","Essen"],
  ["Kuchen","bolo","Essen"],
  ["Teller","o prato","Essen"],
  ["Glas","o copo","Essen"],
  ["Besteck","os talheres","Essen"],
  ["Frühstück","o pequeno-almoço","Essen"],
  ["Speisekarte","a ementa (pt-PT)\n⚠ Nicht 'cardápio' (das ist Brasilien!)","Essen"],
  ["Vorspeise","a entrada","Essen"],
  ["Hauptgericht","o prato principal","Essen"],
  ["Dessert / Nachtisch","a sobremesa","Essen"],
  ["Ich bin Vegetarier/in","Sou vegetariano/a","Essen"],
  ["lecker / köstlich","saboroso/a / delicioso/a","Essen"],
  ["Ich bin allergisch gegen...","Sou alérgico/a a...","Essen"],
  ["zum Mitnehmen","para levar / para fora","Essen"],
  ["gut durchgebraten / medium","bem passado / médio","Essen"],
  ["Guten Appetit!","Bom apetite!","Essen"],

  // --- Transport ---
  ["Auto","o carro","Transport"],
  ["Flughafen","o aeroporto","Transport"],
  ["Flugzeug","o avião","Transport"],
  ["Zug","o comboio","Transport"],
  ["Bus","o autocarro","Transport"],
  ["U-Bahn","o metro","Transport"],
  ["Fahrkarte","o bilhete","Transport"],

  // --- Nomen (allgemein) ---
  ["Koffer","a mala","Nomen"],
  ["Flagge","a bandeira","Nomen"],
  ["Supermarkt","o supermercado","Nomen"],
  ["Arbeit","trabalho","Nomen"],
  ["Doktor (Arzt)","médico","Nomen"],
  ["Portmonee","a carteira","Nomen"],
  ["Geld","o dinheiro","Nomen"],
  ["Buch","o livro","Nomen"],
  ["Krankenhaus","o hospital","Nomen"],
  ["Ordner","pasta","Nomen"],
  ["Aufgabe","exercício","Nomen"],
  ["Schlüssel","a chave","Nomen"],
  ["Rechnung","a conta","Nomen"],
  ["Handy","o telemóvel","Nomen"],
  ["Fenster","a janela","Nomen"],
  ["Himmel","o céu","Nomen"],
  ["Tisch","a mesa","Nomen"],
  ["Wolke","a nuvem / as nuvens","Nomen"],
  ["Computer","o computador","Nomen"],
  ["Lampe","o candeeiro","Nomen"],
  ["Tasche","o saco","Nomen"],
  ["Handtuch","a toalha","Nomen"],
  ["Sonnencreme","o protector solar","Nomen"],
  ["Blätter","as folhas","Nomen"],
  ["Baum","a árvore","Nomen"],
  ["Strand","a praia","Nomen"],
  ["Meer","o mar","Nomen"],

  // --- Orte & Gebäude ---
  ["Apotheke","a farmácia","Orte"],
  ["Bahnhof","a estação","Orte"],
  ["Parkplatz","estacionamento","Orte"],
  ["Platz","a praça","Orte"],
  ["Straße","a rua","Orte"],
  ["Zentrum","o centro","Orte"],
  ["Laden / Geschäft","a loja","Orte"],
  ["Toilette","a casa de banho","Orte"],

  // --- Wohnen ---
  ["Wohnung","o apartamento / a casa","Wohnen"],
  ["Schlafzimmer","o quarto","Wohnen"],
  ["Wohnzimmer","a sala (de estar)","Wohnen"],
  ["Küche","a cozinha","Wohnen"],
  ["Badezimmer","a casa de banho\n⚠ Nicht 'banheiro' (das ist Brasilien!)","Wohnen"],
  ["Bett","a cama","Wohnen"],
  ["Stuhl","a cadeira","Wohnen"],
  ["Schrank","o armário","Wohnen"],
  ["Boden / Fußboden","o chão","Wohnen"],
  ["Decke (Zimmerdecke)","o tecto (pt-PT)\n⚠ Mit 'c' – europäisches Portugiesisch!","Wohnen"],

  // --- Familie & Menschen ---
  ["Eltern","pais","Familie"],
  ["Mama","a mãe","Familie"],
  ["Papa","pai","Familie"],
  ["Kinder","filhos","Familie"],
  ["Schwester","irmã","Familie"],
  ["Bruder","o irmão","Familie"],
  ["Hund","cão","Familie"],
  ["Dr.","doutor","Familie"],
  ["Dra.","doutora","Familie"],
  ["D.","Dona","Familie"],

  // --- Zeit ---
  ["heute","hoje","Zeit"],
  ["morgen","amanhã","Zeit"],
  ["gestern","ontem","Zeit"],
  ["Morgen","manhã","Zeit"],
  ["Frühling","a primavera","Zeit"],
  ["Herbst","o outono","Zeit"],
  ["Sommer","o verão","Zeit"],
  ["Winter","o inverno","Zeit"],
  ["jetzt","agora","Zeit"],
  ["später","depois / mais tarde","Zeit"],
  ["vorher / früher","antes","Zeit"],
  ["immer","sempre","Zeit"],
  ["nie / niemals","nunca / jamais","Zeit"],
  ["manchmal","às vezes","Zeit"],
  ["oft","muitas vezes / frequentemente","Zeit"],
  ["selten","raramente / poucas vezes","Zeit"],
  ["schon / bereits","já","Zeit"],
  ["noch nicht","ainda não","Zeit"],
  ["noch (immer)","ainda","Zeit"],

  // --- Orientierung ---
  ["links","à esquerda","Orientierung"],
  ["rechts","à direita","Orientierung"],
  ["geradeaus","em frente / sempre em frente","Orientierung"],
  ["nah / in der Nähe","perto","Orientierung"],
  ["weit (weg)","longe","Orientierung"],
  ["Ecke","a esquina","Orientierung"],
  ["Kreuzung","o cruzamento","Orientierung"],
  ["nach oben / aufwärts","para cima","Orientierung"],
  ["nach unten / abwärts","para baixo","Orientierung"],

  // --- Zahlen & Mengen ---
  ["einmal / zweimal","uma vez / duas vezes","Zahlen"],
  ["erster / erste","primeiro/a","Zahlen"],
  ["letzter / letzte","último/a","Zahlen"],
  ["nächster / nächste","próximo/a","Zahlen"],

  // --- Grammatik ---
  ["aber","mas","Grammatik"],
  ["mit","com","Grammatik"],
  ["ohne","sem","Grammatik"],
  ["wo","onde","Grammatik"],
  ["Weil","porque","Grammatik"],
  ["auch","também","Grammatik"],
  ["mehr","mais","Grammatik"],
  ["wenig","pouco","Grammatik"],
  ["alles","tudo","Grammatik"],
  ["jemand","alguém","Grammatik"],
  ["in / an (Ort) – Kontraktion","no (= em + o) / na (= em + a)\nz.B. no café, na loja","Grammatik"],
  ["von / aus – Kontraktion","do (= de + o) / da (= de + a)\nz.B. do Porto, da praia","Grammatik"],
  ["zu / nach – Kontraktion","ao (= a + o) / à (= a + a)\nz.B. ao mercado, à estação","Grammatik"],
  ["für","para / por\n(para = Zweck/Richtung, por = Grund/Tausch)","Grammatik"],
  ["über (Thema)","sobre / acerca de","Grammatik"],
  ["zwischen","entre","Grammatik"],
  ["vor (Ort)","em frente de / à frente de","Grammatik"],
  ["hinter","atrás de","Grammatik"],
  ["neben / bei","ao lado de / junto a","Grammatik"],
  ["obwohl / obgleich","embora / apesar de","Grammatik"],
  ["wenn / falls","se","Grammatik"],
  ["damit / sodass","para que","Grammatik"],

  // --- Begrüßungen & Abschied ---
  ["Guten Morgen","Bom dia","Begrüßungen"],
  ["Guten Tag","boa tarde","Begrüßungen"],
  ["Guten Abend","boa noite","Begrüßungen"],
  ["Hallo","olá","Begrüßungen"],
  ["Hi","oi","Begrüßungen"],
  ["Tschüss","adeus","Begrüßungen"],
  ["Tschau","xau","Begrüßungen"],
  ["bis bald","até já","Begrüßungen"],
  ["Bis später","até logo","Begrüßungen"],
  ["bis morgen","até amanhã","Begrüßungen"],
  ["bis zum nächsten Mal","até a próxima","Begrüßungen"],
  ["Wie geht es dir?","como estás","Begrüßungen"],
  ["mir geht es gut","estou bem","Begrüßungen"],
  ["Wie heißt du / Sie?","Como te chamas? (informal)\nComo se chama? (formal)","Begrüßungen"],
  ["Ich heiße...","Chamo-me... / O meu nome é...","Begrüßungen"],

  // --- Redewendungen ---
  ["Okay","Pronto","Redewendungen"],
  ["nicht wirklich","pois não","Redewendungen"],
  ["gleichfalls","igualmente","Redewendungen"],
  ["Du hast recht","Tens razão","Redewendungen"],
  ["vielleicht nein","talvez não","Redewendungen"],
  ["das hier (nahe bei mir)","isto aqui","Redewendungen"],
  ["ohne Zweifel","Sem dúvida","Redewendungen"],
  ["Entschuldigung (falsch machen informell)","desculpa","Redewendungen"],
  ["Komm schon","Vá lá","Redewendungen"],
  ["Ich glaube ja","acho que sim","Redewendungen"],
  ["Ich glaube nicht","acho que não","Redewendungen"],
  ["Macht das Sinn?","Faz sentido?","Redewendungen"],
  ["Bist du dir sicher?","Tens a certeza?","Redewendungen"],
  ["Ich bin mir sicher","Tenho a certeza","Redewendungen"],
  ["Ich glaube auch","também acho","Redewendungen"],
  ["Gut zu wissen","Bom saber","Redewendungen"],
  ["was denkst du?","O que achas?","Redewendungen"],
  ["Es lohnt sich","Vale a pena","Redewendungen"],
  ["Es lohnt sich nicht","Não vale a pena","Redewendungen"],
  ["Vielleicht ja","Talvez sim","Redewendungen"],
  ["Werden wir später sehen","Logo se vê","Redewendungen"],
  ["wir werden sehen","Vamos ver","Redewendungen"],
  ["Kein Problem","Não faz mal.","Redewendungen"],
  ["Man weiß nie","nunca se sabe","Redewendungen"],
  ["keinesfalls","nem pensar","Redewendungen"],
  ["Yeah","Pois","Redewendungen"],
  ["Für alle Fälle","pelo sim, pelo não","Redewendungen"],
  ["Ich weiß nicht","não sei","Redewendungen"],
  ["Ist egal","Tanto faz","Redewendungen"],
  ["Vielen Dank","Muito Obrigado","Redewendungen"],
  ["es könnte schlimmer sein","podia ser pior","Redewendungen"],
  ["nicht immer","Nem sempre","Redewendungen"],
  ["Nicht wirklich","Nem por isso","Redewendungen"],
  ["Ich habe keine Ahnung","não faço ideia","Redewendungen"],
  ["Ich kann es kaum erwarten","mal posso esperar","Redewendungen"],
  ["Lass es sein","deixa estar","Redewendungen"],
  ["Mach es dir bequem","Estar à vontade","Redewendungen"],
  ["einverstanden","Combinado","Redewendungen"],
  ["klingt gut für mich","parece-me bem","Redewendungen"],
  ["genau","claro","Redewendungen"],
  ["Die Rechnung bitte.","A conta, por favor.","Redewendungen"],
  ["Ich hab recht","Tenho razão","Redewendungen"],
  ["Vielleicht","se calhar","Redewendungen"],
  ["übrigens","já agora","Redewendungen"],
  ["bitte","por favor / se faz favor (sff)","Redewendungen"],
  ["Ja","sim","Redewendungen"],
  ["nein","não","Redewendungen"],
  ["wir haben gute Wellen heute","temos boas ondas hoje","Redewendungen"],
  ["Entschuldigung (falsch machen formell)","desculpe","Redewendungen"],
  ["Entschuldigung (bitten)","com licença","Redewendungen"],
  ["Ich möchte...","Queria...\n(höflicher als 'quero' – typisch europäisch-pt!)","Redewendungen"],
  ["Können Sie mir helfen?","Pode ajudar-me?","Redewendungen"],
  ["Ich verstehe nicht","Não percebo / Não entendo","Redewendungen"],
  ["Können Sie das wiederholen?","Pode repetir, por favor?","Redewendungen"],
  ["Langsamer bitte","Mais devagar, por favor","Redewendungen"],
  ["Wie sagt man... auf Portugiesisch?","Como se diz... em português?","Redewendungen"],
  ["Was bedeutet das?","O que é que isso significa?","Redewendungen"],
  ["Ich spreche ein bisschen Portugiesisch","Falo um pouco de português","Redewendungen"],
  ["Wie lange dauert das?","Quanto tempo demora?","Redewendungen"],
  ["Wann...?","Quando...?","Redewendungen"],
  ["Warum?","Porquê? / Por que?","Redewendungen"],
  ["Wie viel kostet das?","Quanto custa? / Quanto é?","Redewendungen"],
  ["Haben Sie...?","Tem...?","Redewendungen"],
  ["nicht wahr? / oder?","não é? / pois não?","Redewendungen"],
  ["Na ja... / Ach so...","Pois...","Redewendungen"],
  ["Zum Wohl!","Saúde!","Redewendungen"],
  ["herzlichen Glückwunsch","parabéns","Redewendungen"],
  ["Viel Glück!","Boa sorte!","Redewendungen"],
  ["Macht nichts / Egal","Não tem mal / Não faz mal","Redewendungen"],
  ["Das stimmt / Stimmt","É verdade / Com certeza","Redewendungen"],
  ["Woher kommst du?","De onde és? (informal)\nDe onde é? (formal)","Redewendungen"],
  ["Ich komme aus Deutschland","Sou da Alemanha / Sou alemão/alemã","Redewendungen"],
];

const CATEGORIES = [
  'Alle', 'Verben', 'Präteritum', 'Adjektive', 'Farben', 'Kleidung', 'Körper',
  'Essen', 'Transport', 'Nomen', 'Orte', 'Wohnen', 'Familie', 'Zeit', 'Orientierung',
  'Zahlen', 'Grammatik', 'Begrüßungen', 'Redewendungen'
];
